---
- name: Install Nginx
  hosts: web_servers
  become: yes  # Run tasks with sudo (root) privileges

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes  # Auto-start Nginx at boot

